import Link from "next/link";
import { directions, edges, papers } from "@/lib/demo-data";
import { AppShell } from "./app-shell";

export function Dashboard() {
  const read = papers.filter((p) => p.readingStatus === "read").length;
  return <AppShell section="Research Overview"><div className="content"><div className="page-head"><div><h1>你的研究，正在形成结构。</h1><p className="subtle">从读过的论文开始，把方法、问题、概念与判断连接成可验证的知识网络。</p></div><Link href="/library" className="btn primary">＋ 添加论文</Link></div>
    <div className="grid cols-4"><div className="card metric"><span className="eyebrow">Library</span><span className="metric-value">{papers.length}</span><span className="metric-note">篇文献 · {read} 篇已读</span></div><div className="card metric"><span className="eyebrow">Knowledge graph</span><span className="metric-value">10</span><span className="metric-note">节点 · {edges.length} 条关系</span></div><div className="card metric"><span className="eyebrow">Notes</span><span className="metric-value">3</span><span className="metric-note">最近更新于 8 月 11 日</span></div><div className="card metric"><span className="eyebrow">Research directions</span><span className="metric-value">{directions.length}</span><span className="metric-note">1 个活跃方向</span></div></div>
    <section className="section grid cols-2"><div className="card direction-card"><span className="eyebrow" style={{color:"#a9bdad"}}>My Research · Active</span><h2>{directions[0].title}</h2><p className="subtle">{directions[0].description}</p><Link href="/research" className="btn" style={{position:"relative",zIndex:1}}>打开研究方向 →</Link></div><div className="card"><div className="section-head"><h2>主要研究主题</h2><span className="meta">按关联项</span></div><div className="topic-bars">{[["Concept Learning",82],["Neuro-symbolic",67],["Ocean Eddy",54],["Explainability",46]].map(([t,v])=><div className="topic-line" key={t}><span>{t}</span><div className="bar"><span style={{width:`${v}%`}}/></div><span>{v}</span></div>)}</div></div></section>
    <section className="section grid cols-2"><div className="card"><div className="section-head"><h2>最近阅读</h2><Link href="/library" className="meta">全部文献 →</Link></div><div className="list">{papers.slice(0,3).map(p=><Link href={`/library/${p.id}`} className="list-row" key={p.id}><div><div className="paper-title">{p.title}</div><div className="meta">{p.authors.slice(0,2).join(", ")} · {p.year}</div></div><span className={`status ${p.readingStatus}`}>{p.readingStatus === "read" ? "已读" : p.readingStatus === "reading" ? "阅读中" : "待读"}</span></Link>)}</div></div><div className="card"><div className="section-head"><h2>最近建立的关系</h2><Link href="/graph" className="meta">打开图谱 →</Link></div><div className="list">{edges.slice(-3).reverse().map(e=><div className="list-row" key={e.id}><div><div className="eyebrow">{e.relationType}</div><div className="meta" style={{marginTop:6}}>{e.evidence}</div></div><span className="tag">{e.createdBy}</span></div>)}</div></div></section>
  </div></AppShell>;
}
