"use client";
import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { papers as demoPapers } from "@/lib/demo-data";
import type { Paper, ReadingStatus } from "@/lib/types";
import { AppShell } from "./app-shell";

const statusLabel: Record<ReadingStatus,string> = { to_read:"待读", reading:"阅读中", read:"已读" };
export function PaperLibrary() {
  const [items,setItems]=useState(demoPapers); const [query,setQuery]=useState(""); const [status,setStatus]=useState("all"); const [year,setYear]=useState("all"); const [topic,setTopic]=useState("all"); const [editing,setEditing]=useState<Paper|null|undefined>(undefined);
  const filtered=useMemo(()=>items.filter(p=>(status==="all"||p.readingStatus===status)&&(year==="all"||String(p.year)===year)&&(topic==="all"||p.tags.includes(topic))&&`${p.title} ${p.authors.join(" ")} ${p.tags.join(" ")} ${p.mySummary}`.toLowerCase().includes(query.toLowerCase())),[items,query,status,year,topic]);
  const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const paper:Paper={id:editing?.id??crypto.randomUUID(),title:String(form.get("title")),authors:String(form.get("authors")).split(",").map(v=>v.trim()).filter(Boolean),year:Number(form.get("year"))||undefined,venue:String(form.get("venue")),tags:String(form.get("tags")).split(",").map(v=>v.trim()).filter(Boolean),readingStatus:String(form.get("status")) as ReadingStatus,mySummary:String(form.get("summary")),myNotes:String(form.get("notes")),updatedAt:new Date().toISOString().slice(0,10)};setItems(curr=>editing?curr.map(p=>p.id===editing.id?paper:p):[paper,...curr]);setEditing(undefined)};
  const remove=(id:string)=>{if(window.confirm("确定删除这篇论文？此操作只影响当前演示会话。"))setItems(curr=>curr.filter(p=>p.id!==id))};
  return <AppShell section="Literature Library"><div className="content"><div className="page-head"><div><h1>Literature Library</h1><p className="subtle">只收录你真正读过或准备阅读的论文，并为每篇论文留下结构化判断。</p></div><button className="btn primary" onClick={()=>setEditing(null)}>＋ 添加论文</button></div>
  <div className="search-row"><input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索标题、作者、标签或摘要…" aria-label="搜索论文"/><select className="field" value={status} onChange={e=>setStatus(e.target.value)} aria-label="阅读状态"><option value="all">全部状态</option><option value="read">已读</option><option value="reading">阅读中</option><option value="to_read">待读</option></select><select className="field" value={year} onChange={e=>setYear(e.target.value)} aria-label="年份"><option value="all">全部年份</option>{[2026,2024,2023,2020].map(y=><option key={y}>{y}</option>)}</select><select className="field" value={topic} onChange={e=>setTopic(e.target.value)} aria-label="研究主题"><option value="all">全部主题</option>{[...new Set(items.flatMap(p=>p.tags))].map(t=><option key={t}>{t}</option>)}</select></div>
  <p className="meta">{filtered.length} 篇论文</p><div className="paper-grid">{filtered.map(p=><article className="card paper-card" key={p.id}><div className="meta">{p.year} · {p.venue}</div><Link href={`/library/${p.id}`} className="paper-title" style={{marginTop:8}}>{p.title}</Link><div className="meta">{p.authors.join(", ")}</div><p className="paper-summary">{p.mySummary || "尚未填写一句话总结。"}</p><div className="tag-row">{p.tags.map(t=><span className="tag" key={t}>{t}</span>)}{p.isDemo&&<span className="tag demo">DEMO</span>}</div><div className="paper-foot"><span className={`status ${p.readingStatus}`}>{statusLabel[p.readingStatus]}</span><div><button className="btn" onClick={()=>setEditing(p)}>编辑</button> <button className="btn danger" onClick={()=>remove(p.id)}>删除</button></div></div></article>)}</div>
  {editing!==undefined&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target)setEditing(undefined)}}><form className="modal" onSubmit={save}><div className="section-head"><h2>{editing?"编辑论文":"添加论文"}</h2><button type="button" className="btn" onClick={()=>setEditing(undefined)}>关闭</button></div><div className="form-grid"><label className="label wide">标题<input required name="title" className="field" defaultValue={editing?.title}/></label><label className="label wide">作者（逗号分隔）<input name="authors" className="field" defaultValue={editing?.authors.join(", ")}/></label><label className="label">年份<input name="year" type="number" className="field" defaultValue={editing?.year}/></label><label className="label">Venue<input name="venue" className="field" defaultValue={editing?.venue}/></label><label className="label">阅读状态<select name="status" className="field" defaultValue={editing?.readingStatus??"to_read"}><option value="to_read">待读</option><option value="reading">阅读中</option><option value="read">已读</option></select></label><label className="label">标签（逗号分隔）<input name="tags" className="field" defaultValue={editing?.tags.join(", ")}/></label><label className="label wide">一句话总结<textarea name="summary" className="field" defaultValue={editing?.mySummary}/></label><label className="label wide">我的笔记<textarea name="notes" className="field" defaultValue={editing?.myNotes}/></label></div><div style={{display:"flex",justifyContent:"flex-end",marginTop:18}}><button className="btn primary">保存论文</button></div></form></div>}</div></AppShell>;
}
